### ISSUE TITLE
Repo not added correctly, Ubuntu 14.04

### ISSUE THREAD

**Issue by aaronkjones** [chef-cookbooks/chef-apt-docker#10]
### Cookbook version
v 2.0.1

### Chef-client version
12.21.1

### Platform Details
Ubuntu 14.04, VM (Virtualbox)

### Scenario:
Adding chef-apt-repo to runlist does not allow for successful chef-client run.

### Steps to Reproduce:
Add chef-apt-docker to empty runlist

### Expected Result:
Get the docker repo

### Actual Result:

`
STDERR: W: Failed to fetch https://download.docker.com/linux/ubuntu/dists/trusty/InRelease  Unable to find expected entry 'stable/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

      E: Some index files failed to download. They have been ignored, or old ones used instead.
      ---- End output of apt-get -q update ----
      Ran apt-get -q update returned 100

      Resource Declaration:
      ---------------------
      # In /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.1/lib/chef/provider/apt_repository.rb

       59:         declare_resource(:apt_update, new_resource.name) do
       60:           ignore_failure true
       61:           action :nothing
       62:         end
       63:

      Compiled Resource:
      ------------------
      # Declared in /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.1/lib/chef/provider/apt_repository.rb:59:in block in <class:AptRepository>

      apt_update("docker-stable") do
        action [:nothing]
        ignore_failure true
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :apt_update
        cookbook_name "chef-apt-docker"
      end

      System Info:
      ------------
      chef_version=12.21.1
      platform=ubuntu
      platform_version=14.04
      ruby=ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
      program_name=chef-client worker: ppid=1786;start=14:31:18;
      executable=/opt/chef/bin/chef-client

  * apt_repository[docker-edge] action remove[2017-08-16T14:31:27-07:00] INFO: Processing apt_repository[docker-edge] action remove (chef-apt-docker::default line 29)
 (up to date)
  * apt_repository[docker-test] action remove[2017-08-16T14:31:27-07:00] INFO: Processing apt_repository[docker-test] action remove (chef-apt-docker::default line 29)
 (up to date)
[2017-08-16T14:31:27-07:00] INFO: Chef Run complete in 7.6820919 seconds

Running handlers:
[2017-08-16T14:31:27-07:00] INFO: Running report handlers
Running handlers complete
[2017-08-16T14:31:27-07:00] INFO: Report handlers complete
Chef Client finished, 5/13 resources updated in 09 seconds
`

` 
cat /etc/apt/sources.list.d/docker-stable.list
deb      "https://download.docker.com/linux/ubuntu" trusty stable
`

**Comment by chasebolt** [comment]
can you verify your VM is running 64bit? docker doesnt support 32bit and that is what the error is complaining about.

**Comment by aaronkjones** [comment]
It is indeed 64bit:
`Name:            Ubuntu 14.04
Groups:          /
Guest OS:        Ubuntu (64-bit)`

**Comment by thedrewster-u51** [comment]
One work-around is to add the following default attributes:
```
default['chef-apt-docker']['docker-stable']['arch'] = 'amd64'
default['chef-apt-docker']['docker-edge']['arch'] = 'amd64'
default['chef-apt-docker']['docker-test']['arch'] = 'amd64'
```
I will submit a pull request with the updated default.rb attributes file.

**Comment by endzyme** [comment]
any update on that pull request?
