### ISSUE TITLE
ERROR: The missing cookbook(s) are: 'apt' version '~> 2.9'

### ISSUE THREAD

**Issue by ajax13** [chef-cookbooks/chef-apt-docker#16]
### Cookbook version
`version":"0.3.0`

### Chef-client version
```
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1
```
### Platform Details
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
### Scenario:
`I want to upload this cookbook to Chef-serever.`

### Steps to Reproduce:
`knife cookbook upload apt-docker --include-dependencies`

### Actual Result:
`Knowing that I have already downloaded and uploaded: 'apt': 6.1.4`
 
```
ERROR: Cookbook apt-docker depends on cookbooks which are not currently
ERROR: being uploaded and cannot be found on the server.
ERROR: The missing cookbook(s) are: 'apt' version '~> 2.9'
```

**Comment by tas50** [comment]
Looks like you'e on a really old version of the cookbook. Try upgrading to the 2.X release. It doesn't require apt

**Comment by ajax13** [comment]
I installed by :  `knife cookbook site install apt-docker`

Looks like the last update in chef supermarket date since 2015!

**Comment by tas50** [comment]
You need to run knife cookbook site install chef-apt-docker. apt-docker is the older cookbook we forked and it has not been updated
