### ISSUE TITLE
rspec failing when including chef-apt-docker::default

### ISSUE THREAD

**Issue by edupo** [chef-cookbooks/chef-apt-docker#2]
### Cookbook version
1.1.0

### Chef-client version
12.18.31

### Platform Details
Ubuntu 16.04 desktop PC

### Scenario:
Performing rspec tests when I include 'chef-apt-docker::default'

### Steps to Reproduce:
    chef generate cookbook test-apt-docker
    cd test-apt-docker
    echo "require 'rspec/core/rake_task'\
    Rspec::Core::RakeTask.new(:unit)\
    task default: [:unit]" > Rakefile
    echo "require 'chef-apt-docker'" >> metadata.rb
    echo "cookbook 'chef-apt-docker'">> Berksfile
    rake

### Expected Result:
No failure

### Actual Result:
```
Failures:

  1) test-remove::default When all attributes are default, on an unspecified platform converges successfully
     Failure/Error: expect { chef_run }.to_not raise_error

       expected no Exception, got #<NoMethodError: undefined method `[]' for nil:NilClass> with backtrace:
         # /tmp/chefspec20170217-9302-15g2jeffile_cache_path/cookbooks/chef-apt-docker/recipes/default.rb:22:in `block in from_file'
         # /tmp/chefspec20170217-9302-15g2jeffile_cache_path/cookbooks/chef-apt-docker/recipes/default.rb:20:in `from_file'
         # /tmp/chefspec20170217-9302-15g2jeffile_cache_path/cookbooks/test-remove/recipes/default.rb:7:in `from_file'
         # ./spec/unit/recipes/default_spec.rb:13:in `block (3 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (4 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'

Finished in 1.36 seconds (files took 1.55 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/unit/recipes/default_spec.rb:16 # test-remove::default When all attributes are default, on an unspecified platform converges successfully

/opt/chefdk/embedded/bin/ruby -I/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib:/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed

```

**Comment by tas50** [comment]
What version of Chefspec are you running? Older versions don't support apt_repository.

**Comment by edupo** [comment]
`5.3.0`, the one included on the latest chef-dk: `/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chefspec-5.3.0`

**Comment by iennae** [comment]
Based on my (limited) testing, this appears like either a chefspec, or chef dk specific issue. 
The chef-apt-docker cookbook itself passes chef spec locally. 

> ➜  chef-apt-docker git:(master) chef exec rspec
> 
> default recipe on ubuntu 16.04
>   converges successfully
> 
> Top 1 slowest examples (0.00025 seconds, 0.0% of total time):
>   default recipe on ubuntu 16.04 converges successfully
>     0.00025 seconds ./spec/unit/recipes/default_spec.rb:7
> 
> Finished in 24.88 seconds (files took 4.08 seconds to load)
> 1 example, 0 failures

I can replicate the error:

> ➜  test-apt-docker git:(master) ✗ chef exec rspec ./spec/unit/recipes/default_spec.rb
> WARNING: you must specify a platform and platform_version to your ChefSpec Runner and/or Fauxhai constructor, in the future omitting these will become a hard error
> F
> 
> Failures:
> 
>   1) test-apt-docker::default converges successfully
>      Failure/Error: expect { chef_run }.to_not raise_error
> 
>        expected no Exception, got #<NoMethodError: undefined method `[]' for nil:NilClass> with backtrace:
>          # /var/folders/cg/kg0_zhvs3xv9xblhm55zhy6r0000gp/T/chefspec20170301-69060-c81giefile_cache_path/cookbooks/chef-apt-docker/recipes/default.rb:22:in `block in from_file'
>          # /var/folders/cg/kg0_zhvs3xv9xblhm55zhy6r0000gp/T/chefspec20170301-69060-c81giefile_cache_path/cookbooks/chef-apt-docker/recipes/default.rb:20:in `from_file'
>          # /var/folders/cg/kg0_zhvs3xv9xblhm55zhy6r0000gp/T/chefspec20170301-69060-c81giefile_cache_path/cookbooks/test-apt-docker/recipes/default.rb:7:in `from_file'
>          # ./spec/unit/recipes/default_spec.rb:13:in `block (2 levels) in <top (required)>'
>          # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'
>          # ./spec/unit/recipes/default_spec.rb:17:in `block (2 levels) in <top (required)>'
>      # ./spec/unit/recipes/default_spec.rb:17:in `block (2 levels) in <top (required)>'
> 
> Top 1 slowest examples (0.23873 seconds, 70.0% of total time):
>   test-apt-docker::default converges successfully
>     0.23873 seconds ./spec/unit/recipes/default_spec.rb:16
> 
> Finished in 0.3412 seconds (files took 3.74 seconds to load)
> 1 example, 1 failure
> 
> Failed examples:
> 
> rspec ./spec/unit/recipes/default_spec.rb:16 # test-apt-docker::default converges successfully
> 

If I modify the default spec that is generated with the cookbook generator to specify the platform (example as in this cookbook itself https://github.com/chef-cookbooks/chef-apt-docker/blob/master/spec/unit/recipes/default_spec.rb) I don't get the error:

Top 1 slowest examples (0.00034 seconds, 0.3% of total time):
  default recipe on ubuntu 16.04 converges successfully
    0.00034 seconds ./spec/unit/recipes/default_spec.rb:13

Finished in 0.09761 seconds (files took 2.43 seconds to load)
1 example, 0 failures

If I follow this same example of steps with httpd, I get the same kind of error of failure (prior to modifying the spec).

Version information:

> ➜  test-apt-docker git:(master) ✗ ls /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chefspec-5.4.0/
> ➜  test-apt-docker git:(master) ✗ chef --version
> Chef Development Kit Version: 1.3.10
> chef-client version: 12.18.31
> delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
> berks version: 5.6.2
> kitchen version: 1.15.0

@tas50 may have more insight into whether this is a chefspec issue, or if this is an enhancement that needs to be made to fix the default spec created when chef cookbook generate is done.

**Comment by tas50** [comment]
This looks like an issue with the default Chefspec code we generate with Chef-DK. I filed a bug for the fix there https://github.com/chef/chef-dk/issues/1201. If you specify the platform and platform version in the default chefspec you should get a clean converge here.
