### ISSUE TITLE
key pulling no longer works with 1.1.2 ( or not yet fixed )

### ISSUE THREAD

**Issue by EugenMayer** [chef-cookbooks/chef-apt-docker#7]
### Cookbook version
1.1.2

### Chef-client version
13

### Platform Details
debian stretch (9)

### Scenario:
running test kitchen

### Steps to Reproduce:
just include 
```
include_recipe 'chef-apt-docker'
```

### Expected Result:
not exceptions

### Actual Result:
```
Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           execute[install-key 58118E89F3A912897C070ADBF76221572C52609D] (/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider/apt_repository.rb line 196) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
           ---- Begin output of apt-key adv --recv --keyserver hkp://pgp.mit.edu:80 58118E89F3A912897C070ADBF76221572C52609D ----
           STDOUT: Executing: /tmp/apt-key-gpghome.bY6FoKrRNq/gpg.1.sh --recv --keyserver hkp://pgp.mit.edu:80 58118E89F3A912897C070ADBF76221572C52609D
           STDERR: Warning: apt-key output should not be parsed (stdout is not a terminal)
           gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
           gpg: connecting dirmngr at '/tmp/apt-key-gpghome.bY6FoKrRNq/S.dirmngr' failed: No such file or directory
           gpg: keyserver receive failed: No dirmngr
           ---- End output of apt-key adv --recv --keyserver hkp://pgp.mit.edu:80 58118E89F3A912897C070ADBF76221572C52609D ----
           Ran apt-key adv --recv --keyserver hkp://pgp.mit.edu:80 58118E89F3A912897C070ADBF76221572C52609D returned 2
```

**Comment by EugenMayer** [comment]
probably related to debian stretch, seems you only test up to jessie: https://github.com/chef-cookbooks/chef-apt-docker/blob/master/.kitchen.yml#L13

might be related to this checkin https://github.com/chef-cookbooks/chef-apt-docker/commit/bd4415a7b596f4de23a93219b03c0bbcfee31e53

**Comment by EugenMayer** [comment]
confirmed, its related to debian stretch, debain jessie works. Maybe this boils down to the new gpg.d key way of distributing keys under stretch?

**Comment by EugenMayer** [comment]
The issue is that we need to install `dirmngr`

**Comment by tas50** [comment]
@EugenMayer Exactly what version of Chef 13 are you using? We did make some changes to how this is handled recently in chef-client.

**Comment by EugenMayer** [comment]
It's test kitchen, so most probably the newest 13.x .. beside that installing dirmngr does fix this and iam prettying sure that is not handled by chef internally

**Comment by tas50** [comment]
@EugenMayer https://github.com/chef-cookbooks/chef-apt-docker/pull/9 should fix it

**Comment by EugenMayer** [comment]
That's wrong, since you need transport-https under Debian 8 too, you need to split those conditions

**Comment by tas50** [comment]
The real fix here is to apply the apt cookbook and get the https support, which for some reason in 2017 debian still doesn't think belongs in the base OS. This will workaround the issue on Debian 9 though.
